services:
  server:
    build:
      context: ./server
    ports:
      - "5005:5005"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    depends_on:
      - db

  client:
    build:
      context: ./client
    ports:
      - "2107:80"

  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
