services:
  server:
    build:
      context: ./server
    ports:
      - "5005:5005"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    networks:
      - app_network
    depends_on:
      - db

  client:
    build:
      context: ./client
    ports:
      - "2107:80"
    networks:
      - app_network

  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: xxx
      MONGO_INITDB_ROOT_PASSWORD: XXX
    volumes:
      - artswap-project_mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: --bind_ip 0.0.0.0 # Permet à MongoDB d'écouter sur toutes les interfaces réseau
    networks:
      - app_network

volumes:
  artswap-project_mongo_data:
  artswap-project_new_mongo_data:
  mongodb_data:

networks:
  app_network:
    driver: bridge
